[package]
name = "rusters"
version = "0.1.0"
authors = ["Frankie Baffa <frankie.baffa@gentryhealthservices.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.base64]
version = "0.13"

[dependencies.sha3]
version = "0.9"

[dependencies.sqlite]
version = "0.26"

