[package]
name = "rusters"
version = "0.1.0"
authors = ["Frankie Baffa <frankie.baffa@gentryhealthservices.com>"]
edition = "2018"

[[bin]]
name = "migrate_up"
path = "./src/bin/migrate_up.rs"

[dependencies]
base64 = "0.13"
dotenv = "0.15"
migaton = { path = "./migaton" }
rusqlite = { version = "0.25", features = ["bundled"] }
sha3 = "0.9"
worm = { path = "./worm" }
worm_derive = { path = "./worm_derive" }

